In [ ]:
# verify behaviour

In [1]:
import numpy as np
import pandas as pd

In [2]:
from dicemodel.noDICE_v7 import PyDICE

In [20]:

model = PyDICE()
model.__call__(miu_period=58)

{'Atmospheric Temperature': array([0.8       , 0.92545486, 1.0588161 , 1.19901815, 1.34516749,
        1.496443  , 1.65204155, 1.81115397, 1.97296001, 2.13663437,
        2.30135811, 2.46633168, 2.63078744, 2.79400026, 2.95529576,
        3.11405611, 3.26972335, 3.42180078, 3.56985259, 3.71105219,
        3.84541525, 3.97296426, 4.09373116, 4.20775884, 4.31510164,
        4.41582523, 4.51000611, 4.59773068, 4.67909423, 4.75419983,
        4.82315706, 4.88608097, 4.94309084, 4.99430922, 5.03986089,
        5.07987198, 5.11446916, 5.14377895, 5.16792699, 5.18703758,
        5.20123313, 5.21063373, 5.21535681, 5.21551683, 5.21122498,
        5.20258902, 5.18971303, 5.1726973 , 5.15163819, 5.12662802,
        5.09775499, 5.0651031 , 5.02875211, 4.98877746, 4.94525025,
        4.89823716, 4.84780047, 4.79399793, 4.7368828 , 4.67827952,
        4.61909759, 4.56005544, 4.50171235, 4.44449565, 4.38872395]),
 'Per Capita Damage': array([ 0.29248318,  0.27614808,  0.26274088,  0.25165734,  0.242

In [21]:
# model.inst_disutil_dam
# model.sdr_dam
model.emdd

-0.55

In [22]:
model.miu_period

58

In [23]:
model.miu

array([0.03      , 0.05068966, 0.07137931, 0.09206897, 0.11275862,
       0.13344828, 0.15413793, 0.17482759, 0.19551724, 0.2162069 ,
       0.23689655, 0.25758621, 0.27827586, 0.29896552, 0.31965517,
       0.34034483, 0.36103448, 0.38172414, 0.40241379, 0.42310345,
       0.4437931 , 0.46448276, 0.48517241, 0.50586207, 0.52655172,
       0.54724138, 0.56793103, 0.58862069, 0.60931034, 0.63      ,
       0.65068966, 0.67137931, 0.69206897, 0.71275862, 0.73344828,
       0.75413793, 0.77482759, 0.79551724, 0.8162069 , 0.83689655,
       0.85758621, 0.87827586, 0.89896552, 0.91965517, 0.94034483,
       0.96103448, 0.98172414, 1.00241379, 1.02310345, 1.0437931 ,
       1.06448276, 1.08517241, 1.10586207, 1.12655172, 1.14724138,
       1.16793103, 1.18862069, 1.20931034, 1.2       , 1.2       ,
       1.2       , 1.2       , 1.2       , 1.2       , 1.2       ])

In [13]:
model.inst_util_con

array([0.29474721, 0.34074562, 0.38479148, 0.42626671, 0.46494208,
       0.50081091, 0.53398534, 0.56463503, 0.59295208, 0.61913176,
       0.64336232, 0.66582009, 0.68666748, 0.70605258, 0.72410957,
       0.74095967, 0.7567121 , 0.7714652 , 0.78530747, 0.79832695,
       0.81059515, 0.82217594, 0.83312653, 0.84349827, 0.85333728,
       0.86268509, 0.8715791 , 0.88005304, 0.88813732, 0.89601106])

In [24]:
model.e

array([ 36.85300011,  39.70556376,  42.77750264,  45.96055896,
        49.16286924,  52.30773544,  55.33201287,  58.18445514,
        60.82416316,  63.21919093,  65.34531724,  67.18497374,
        68.72631262,  69.96239616,  70.89049093,  71.51145152,
        71.82918092,  71.85015629,  71.58301128,  71.03816705,
        70.22798624,  69.16580927,  67.86574656,  66.34248805,
        64.61113033,  62.68702106,  60.58561999,  58.32237581,
        55.91261768,  53.37146055,  50.71372301,  47.95385699,
        45.1058879 ,  42.18336469,  39.19931871,  36.16623065,
        33.0960048 ,  29.99994983,  26.88876566,  23.77253547,
        20.66072262,  17.56217169,  14.48511332,  11.43717235,
         8.42537871,   5.45618092,   2.53546161,  -0.3314451 ,
        -3.13973481,  -5.88511284,  -8.56377318, -11.17237688,
       -13.70802979, -16.16826007, -18.55099549, -20.85454081,
       -23.07755518, -25.2190299 , -23.7202307 , -23.33996357,
       -22.95672531, -22.5709942 , -22.18325092, -21.79

In [11]:
model.e

array([ 36.85300011,  38.89774181,  40.96531142,  42.9334168 ,
        44.7014743 ,  46.18877224,  47.33224001,  48.08420524,
        48.41029981,  48.2875697 ,  47.70279613,  46.65101573,
        45.13422054,  43.16021782,  40.74163049,  37.89502144,
        34.64012691,  30.99918611,  26.99635604,  22.65720191,
        18.0083618 ,  13.07690882,   7.8900732 ,   2.47499982,
        -3.14146061,  -8.9329292 , -14.87364793, -20.93860253,
       -27.10362163, -28.99538109, -29.21799082, -29.40798744,
       -29.56463419, -29.68759782, -29.77687975, -29.83276234,
       -29.85576507, -29.84660739, -29.80617632, -29.73549784,
       -29.63571125, -29.50804623, -29.35380239, -29.17433095,
       -28.97101863, -28.74527343, -28.49851223, -28.23215001,
       -27.94759059, -27.64621878, -27.32939365, -26.99844301,
       -26.65465877, -26.29929321, -25.93355599, -25.55861186,
       -25.17557888, -24.78552724, -24.38947845, -23.98840498,
       -23.58323018, -23.17482856, -22.7640262 , -22.35

In [18]:
model.abatecost

array([2.31366005e-04, 7.79246594e+00, 8.38652535e+00, 9.01975704e+00,
       9.67078010e+00, 1.03219398e+01, 1.09591839e+01, 1.15716246e+01,
       1.21510286e+01, 1.26913373e+01, 1.31882530e+01, 1.36388965e+01,
       1.40415277e+01, 1.43953209e+01, 1.47001827e+01, 1.49566056e+01,
       1.51655480e+01, 1.53283374e+01, 1.54465898e+01, 1.55221446e+01,
       1.55570226e+01, 1.55533524e+01, 1.55133379e+01, 1.54392296e+01,
       1.53333009e+01, 1.51978937e+01, 1.50354460e+01, 1.48483278e+01,
       1.46388356e+01, 1.44091879e+01, 1.41615222e+01, 1.38978903e+01,
       1.36202554e+01, 1.33304891e+01, 1.30303689e+01, 1.27215771e+01,
       1.24056997e+01, 1.20842260e+01, 1.17585497e+01, 1.14299694e+01,
       1.10996901e+01, 1.07688256e+01, 1.04384004e+01, 1.01093527e+01,
       9.78253742e+00, 9.45872911e+00, 9.13862573e+00, 8.82285202e+00,
       8.51196318e+00, 8.20644860e+00, 7.90673559e+00, 7.61319312e+00,
       7.32613554e+00, 7.04582623e+00, 6.77248121e+00, 6.50627259e+00,
      

In [19]:
model.damages

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [9]:
model.damages

array([ 2.        ,  2.        ,  2.        ,  2.        ,  2.        ,
        2.        ,  2.        ,  2.        ,  2.02024881,  2.62078398,
        3.33944619,  4.18491268,  5.16369033,  6.27965487,  7.53364109,
        8.9230929 , 10.44177785, 12.07956765, 13.82228308, 15.62788498,
       17.47068755, 19.32134584, 21.14699376, 22.91142146, 24.57529237,
       26.09640314, 27.42999411, 28.5291242 , 29.34513332, 29.82822881,
       29.99068793, 29.86570545, 29.48511329, 28.88055677, 28.0827072 ,
       27.12073614, 26.02199216, 24.81183097, 23.51355869, 22.14845582,
       20.73585612, 19.29326037, 17.83646962, 16.37972647, 14.93585611,
       13.51640131, 12.13174773, 10.79123728,  9.5032686 ,  8.27538455,
        7.11434708,  6.02620067,  5.01632518,  4.08947979,  3.24983916,
        2.50102329,  2.        ,  2.        ,  2.        ,  2.        ,
        2.        ,  2.        ,  2.        ,  2.        ,  2.        ])

In [15]:
model.c

array([ 47.66830302,  56.53021315,  66.58338413,  77.82271395,
        90.23766023, 103.81397003, 118.53478325, 134.38142751,
       151.33406813, 169.37228916, 188.47563542, 208.62412234,
       229.79871013, 251.98173525, 275.15729224, 299.31156083,
       324.4330755 , 350.51293711, 377.54496837, 405.54362624,
       434.51349056, 464.46126173, 495.3957076 , 527.32755949,
       560.2693619 , 594.2352768 , 629.24083832, 665.30264781,
       702.43799053, 741.4300839 ])

In [16]:
model.y

array([ 63.47310655,  75.2732532 ,  88.65963267, 103.62545133,
       120.15667141, 138.23431429, 157.83592976, 178.93665447,
       201.5100774 , 225.52901353, 250.96622559, 277.79510298,
       305.99029312, 335.52827596, 366.38787249, 398.5506802 ,
       432.00143209, 466.72827844, 502.72299384, 540.00482855,
       578.5798809 , 618.45707287, 659.64807936, 702.16718973,
       746.03110772, 791.25869082, 837.8706236 , 885.88901174,
       935.33687154, 987.2571024 ])

In [17]:
model.undiscounted_welfare

array([ 0.29474721,  0.34074562,  0.38479148,  0.42626671,  0.46494208,
        0.50081091,  0.53398534,  0.56463503,  0.59295208,  0.61913176,
        0.64336232,  0.66582009,  0.68666748,  0.70605258,  0.72410957,
        0.74095967,  0.7567121 ,  0.7714652 ,  0.78530747,  0.79832695,
        0.81059515,  0.82217594,  0.73903548,  0.57063648,  0.41099237,
        0.2647766 ,  0.13697594,  0.03283153, -0.04223623, -0.08257206])

In [20]:
model.disc_disutil_dam[-1]


0.14085825913641092

In [ ]:
tstep = 5
t= 10

prtp_dam = 0.015
emdd = 1.45/2
dam_g = 0.16
dpc = 0.7/10

prtp_con = 0.015
emuc = 1.45
con_g = 0.09
cpc = 20/10

In [ ]:
sdr_dam = (prtp_dam + (emdd * dam_g))
sdr_con = (prtp_con + (emuc * con_g))

# sdr_con = 0.015
# sdr_dam= sdr_con

print(sdr_dam, sdr_con)

In [ ]:
# Social discount factor for disutility of damage            
damage_sdf = (1.0 /(1.0 + sdr_dam))**(tstep * (t))
consumption_sdf = (1.0 /(1.0 + sdr_con))**(tstep * (t))

# print(damage_sdf, consumption_sdf)

In [ ]:
inst_disutil_dam = ((dpc ** (1.0 - emdd)-1.0)/ (1.0 - emdd)- 1.0)
# inst_disutil_dam = np.log(dpc)
inst_util_con = ((cpc ** (1.0 - emuc))/ (1.0 - emuc))


print(inst_disutil_dam, inst_util_con)
print(inst_util_con-inst_disutil_dam)

# print(inst_util_con+inst_disutil_dam)


In [ ]:
uc_marginal = inst_util_con/cpc

vd_marginal = inst_disutil_dam/dpc
print(uc_marginal)

print(vd_marginal)

In [ ]:
disc_disutil_dam = inst_disutil_dam * damage_sdf
disc_util_con = inst_util_con * consumption_sdf

print(disc_disutil_dam,disc_util_con)
print(disc_util_con - disc_disutil_dam)


In [ ]:
prtp_con = 0.015
emuc = 1.45
con_g = 0.09
cpc = 200
sdr_con = (prtp_con + (emuc * con_g))
# print(sdr_con)
consumption_sdf = (1.0 /(1.0 + sdr_con))**(tstep * (t))
# print(consumption_sdf)
inst_util_con = ((cpc ** (1.0 - emuc))/ (1.0 - emuc))
print(inst_util_con)
print(inst_util_con-inst_disutil_dam)
disc_util_con = inst_util_con * consumption_sdf

# print(disc_util_con*1000)
# print((disc_util_con - disc_disutil_dam) * 1000)