In [ ]:
# verify behaviour

In [2]:
import numpy as np
import pandas as pd

In [1]:
from dicemodel.noDICE_v5 import PyDICE
model = PyDICE(steps=10)
model.__call__()

{'Atmospheric Temperature': array([0.8       , 0.92545486, 1.05816026, 1.19646513, 1.33895362,
        1.48434219, 1.63142284, 1.77903606, 1.92606159, 2.07141899]),
 'Per Capita Damage': array([0.29248318, 0.27614808, 0.26274088, 0.25165734, 0.24243748,
        0.23472646, 0.22824716, 0.22278078, 0.22036145, 0.2807157 ]),
 'Per Capita Consumption': array([ 6.97108848,  7.80535498,  8.74708853,  9.79232857, 10.93849564,
        12.18394293, 13.52761407, 14.96879967, 16.50697416, 18.14169383]),
 'Population': array([6838.        , 7242.49099028, 7612.06244902, 7947.31440834,
        8249.54940737, 8520.55616332, 8762.4308785 , 8977.43509798,
        9167.88665673, 9336.07912905]),
 'Utility of Consumption': array([0.29474721, 0.34074562, 0.38479148, 0.42626671, 0.46494208,
        0.50081091, 0.53398534, 0.56463503, 0.59295208, 0.61913176]),
 'Disutility of Damage': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'Welfare': array([-3854.94153823, -3854.85616684, -3854.81394867, -3854.7

In [5]:
# model.inst_disutil_dam
# model.sdr_dam
model.VD_switch

AttributeError: 'PyDICE' object has no attribute 'VD_switch'

In [4]:
model.inst_disutil_dam

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
model.inst_util_con

array([0.29474721, 0.34074562, 0.38479148, 0.42626671, 0.46494208,
       0.50081091, 0.53398534, 0.56463503, 0.59295208, 0.61913176,
       0.64336232, 0.66582009, 0.68666748, 0.70605258, 0.72410957,
       0.74095967, 0.7567121 , 0.7714652 , 0.78530747, 0.79832695,
       0.81059515, 0.82217594, 0.83312653, 0.84349827, 0.85333728,
       0.86268509, 0.8715791 , 0.88005304, 0.88813732, 0.89601106])

In [14]:
model.damages

array([ 2.        ,  2.        ,  2.        ,  2.        ,  2.        ,
        2.        ,  2.        ,  2.        ,  2.02024881,  2.62078398,
        3.33944619,  4.18491268,  5.16369033,  6.27965487,  7.53364109,
        8.9230929 , 10.44177785, 12.07956765, 13.82228308, 15.62788498,
       17.47068755, 19.32134584, 21.14699376, 22.91142146, 24.57529237,
       26.09640314, 27.42999411, 28.5291242 , 29.34513332, 29.82822881])

In [15]:
model.c

array([ 47.66830302,  56.53021315,  66.58338413,  77.82271395,
        90.23766023, 103.81397003, 118.53478325, 134.38142751,
       151.33406813, 169.37228916, 188.47563542, 208.62412234,
       229.79871013, 251.98173525, 275.15729224, 299.31156083,
       324.4330755 , 350.51293711, 377.54496837, 405.54362624,
       434.51349056, 464.46126173, 495.3957076 , 527.32755949,
       560.2693619 , 594.2352768 , 629.24083832, 665.30264781,
       702.43799053, 741.4300839 ])

In [16]:
model.y

array([ 63.47310655,  75.2732532 ,  88.65963267, 103.62545133,
       120.15667141, 138.23431429, 157.83592976, 178.93665447,
       201.5100774 , 225.52901353, 250.96622559, 277.79510298,
       305.99029312, 335.52827596, 366.38787249, 398.5506802 ,
       432.00143209, 466.72827844, 502.72299384, 540.00482855,
       578.5798809 , 618.45707287, 659.64807936, 702.16718973,
       746.03110772, 791.25869082, 837.8706236 , 885.88901174,
       935.33687154, 987.2571024 ])

In [17]:
model.undiscounted_welfare

array([ 0.29474721,  0.34074562,  0.38479148,  0.42626671,  0.46494208,
        0.50081091,  0.53398534,  0.56463503,  0.59295208,  0.61913176,
        0.64336232,  0.66582009,  0.68666748,  0.70605258,  0.72410957,
        0.74095967,  0.7567121 ,  0.7714652 ,  0.78530747,  0.79832695,
        0.81059515,  0.82217594,  0.73903548,  0.57063648,  0.41099237,
        0.2647766 ,  0.13697594,  0.03283153, -0.04223623, -0.08257206])

In [20]:
model.disc_disutil_dam[-1]


0.14085825913641092

In [ ]:
tstep = 5
t= 10

prtp_dam = 0.015
emdd = 1.45/2
dam_g = 0.16
dpc = 0.7/10

prtp_con = 0.015
emuc = 1.45
con_g = 0.09
cpc = 20/10

In [ ]:
sdr_dam = (prtp_dam + (emdd * dam_g))
sdr_con = (prtp_con + (emuc * con_g))

# sdr_con = 0.015
# sdr_dam= sdr_con

print(sdr_dam, sdr_con)

In [ ]:
# Social discount factor for disutility of damage            
damage_sdf = (1.0 /(1.0 + sdr_dam))**(tstep * (t))
consumption_sdf = (1.0 /(1.0 + sdr_con))**(tstep * (t))

# print(damage_sdf, consumption_sdf)

In [ ]:
inst_disutil_dam = ((dpc ** (1.0 - emdd)-1.0)/ (1.0 - emdd)- 1.0)
# inst_disutil_dam = np.log(dpc)
inst_util_con = ((cpc ** (1.0 - emuc))/ (1.0 - emuc))


print(inst_disutil_dam, inst_util_con)
print(inst_util_con-inst_disutil_dam)

# print(inst_util_con+inst_disutil_dam)


In [ ]:
uc_marginal = inst_util_con/cpc

vd_marginal = inst_disutil_dam/dpc
print(uc_marginal)

print(vd_marginal)

In [ ]:
disc_disutil_dam = inst_disutil_dam * damage_sdf
disc_util_con = inst_util_con * consumption_sdf

print(disc_disutil_dam,disc_util_con)
print(disc_util_con - disc_disutil_dam)


In [ ]:
prtp_con = 0.015
emuc = 1.45
con_g = 0.09
cpc = 200
sdr_con = (prtp_con + (emuc * con_g))
# print(sdr_con)
consumption_sdf = (1.0 /(1.0 + sdr_con))**(tstep * (t))
# print(consumption_sdf)
inst_util_con = ((cpc ** (1.0 - emuc))/ (1.0 - emuc))
print(inst_util_con)
print(inst_util_con-inst_disutil_dam)
disc_util_con = inst_util_con * consumption_sdf

# print(disc_util_con*1000)
# print((disc_util_con - disc_disutil_dam) * 1000)